[api]

[docker]
domain = "do.rael.io"
watch = true

[file]

watch = true

[frontends]

  [frontends.github]
  backend = "github"
  passHostHeader = true

    [frontends.github.routes.main]
    rule = "Host:do.rael.io"

[backends]

	[backends.github]

		[backends.github.servers.github]
		url = "https://raelga.github.io:443"
